# Generated by Django 5.0.1 on 2024-03-10 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_commande'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commande',
            old_name='adress',
            new_name='address',
        ),
    ]
