# Generated by Django 5.0.1 on 2024-03-10 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_rename_adress_commande_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commande',
            old_name='zipecode',
            new_name='zipcode',
        ),
    ]
